### ISSUE TITLE
Not all messages being delivered?

### ISSUE THREAD

**Issue by josdejong** [boyers/socket.js#4]
I just started using socket.js, but I encountered some weird behavior. It may be my usage of the library or something, not sure. What I basically do is:
- Take the "Example client" and "Example server" code from the README, get that running (that works fine).
- In the client, replace the following code:
  
  ``` js
  // periodically send messages the server
  var interval = setInterval(function() {
    socket.send('greeting', 'Hello from the client!');
  }, 1000);
  ```
  
  with:
  
  ``` js
  socket.send('greeting', {foo: 'bar1'});
  socket.send('greeting', {foo: 'bar2'});
  socket.send('greeting', {foo: 'bar3'});
  socket.send('greeting', {foo: 'bar4'});
  socket.send('greeting', {foo: 'bar5'});
  ```
- when I restart the server and open a client, only three of the five messages are delivered:
  
  ```
  Received: {"foo":"bar1"}
  Received: {"foo":"bar2"}
  Received: {"foo":"bar3"}
  ```

Am I overlooking something obvious here?

**Comment by stepchowfun** [comment]
Very weird—I'll look into this today. Thanks for catching it!

**Comment by stepchowfun** [comment]
Fixed in https://github.com/boyers/socket.js/commit/fa8795b5bfabd097b57c2e2b2262fcb267a17cff. Thanks again for reporting this!

**Comment by josdejong** [comment]
thanks
